version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
      - '4469:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: root
            password: prisma
            rawAccess: true
            migrations: true

  # Postgres database.
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: root # define credentials
      POSTGRES_PASSWORD: prisma # define credentials
    ports:
      - 5434:5432 # Postgres port
