version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4467:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5433
            user: root
            password: prisma

  # Postgres database.
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: root # define credentials
      POSTGRES_PASSWORD: prisma # define credentials
    ports:
      - 5433:5432 # Postgres port
